name: Nexus Repository
on:
  pull_request:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:  
    runs-on: ubuntu-latest
    steps:
    - run: echo "checkout code"
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Nexus Repo Publish
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
      run: |
        npm install -g npm-cli-login
        npm-cli-login -u "$NEXUS_USER" -p "$NEXUS_PW" -e "gstengel@unchained.com" -r "https://artifacts.unchained-capital.us/repository/npm-stengel/"
        npm publish --registry="https://artifacts.unchained-capital.us/repository/npm-stengel/" ./random-words-1.1.2.tgz
