name: Nexus Repository
on:
  pull_request:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:  
    runs-on: ubuntu-latest
    steps:
    - run: echo "checkout code"
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://artifacts.unchained-capital.us/
        username: ${{ secrets.nxrm_user }}
        password: ${{ secrets.nxrm_password }}
        format: npm
        repository: npm-stengel
        coordinates: asset=my-test-file.tgz
        filename: ./my-test-file.tgz
